name: 显示博客最新文章

# 这个部分用来指定能够触发工作流执行的事件
on:
  workflow_dispatch:

# 工作流是由一个或多个的jobs构成的，在jobs里来说明要交给GitHub aciton执行的任务
jobs:
  # 这个jobs中的一个任务，名字叫build(随便怎么取)
  build:
    # 用来指定这个任务在什么操作系统上跑(服务器是GitHub免费提供的)
    runs-on: ubuntu-latest

    # 指出这个build任务的步骤
    steps:
      # 首先copy git仓库到虚拟机上
      - name: 检查分支
        uses: actions/checkout@v2
        
      - name: 拉取博客最新文章
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: https://qzkyl.ml/atom.xml
        
